name: "Data Platform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # JOB 1: Validação de Qualidade do Código (CI)
  continuous-integration:
    name: "Terraform Lint & Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format Check (Verifica formatação padrão)
        run: terraform -chdir=terraform fmt -check
        description: "Verifica se o código Terraform segue as regras padrão de formatação"

      - name: Terraform Init (Inicializa provedores locais)
        run: terraform -chdir=terraform init -backend=false
        description: "Inicializa os provedores locais para validação sem precisar conectar ao state"

      - name: Terraform Validate (Valida sintaxe e referências AWS)
        run: terraform -chdir=terraform validate
        description: "Valida se a sintaxe e as referências dos recursos na AWS estão corretas"

  # JOB 2: Deploy dos Scripts PySpark para o S3 (CD)
  continuous-deployment:
    name: "Deploy Scripts to S3"
    needs: continuous-integration # Só roda se o teste do Terraform passar
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Sincronizar Scripts com o S3
        run: |
          # Sincroniza apenas a pasta dos scripts com o diretório correto do Data Lake
          # Substitua pelo nome real que você definiu na variável do Terraform ou passe via secret
          aws s3 sync src/glue_jobs/ s3://p2c-olist-lakehouse-dev-storage/scripts/ --delete